--- Register desert biomes
core.register_biome({
	name = "desert",
	node_top = "basenodes:desert_sand",
	depth_top = 1,
	node_filler = "basenodes:desert_sand",
	depth_filler = 1,
	node_stone = "basenodes:desert_stone",
	node_riverbed = "basenodes:sand",
	depth_riverbed = 2,
	node_dungeon = "basenodes:desert_stone",
	--node_dungeon_stair = "stairs:stair_desert_stone",
	y_max = 31000,
	y_min = 4,
	heat_point = 92,
	humidity_point = 16,
	weight = DESERT_WEIGHT,
})

core.register_biome({
	name = "desert_ocean",
	node_top = "basenodes:sand",
	depth_top = 1,
	node_filler = "basenodes:sand",
	depth_filler = 3,
	node_stone = "basenodes:desert_stone",
	node_riverbed = "basenodes:sand",
	depth_riverbed = 2,
	node_cave_liquid = "basenodes:water_source",
	node_dungeon = "basenodes:desert_stone",
	--node_dungeon_stair = "stairs:stair_desert_stone",
	vertical_blend = 1,
	y_max = 3,
	y_min = -255,
	heat_point = 92,
	humidity_point = 16,
	weight = DESERT_WEIGHT,
})

core.register_biome({
	name = "desert_under",
	node_cave_liquid = {"basenodes:water_source", "basenodes:lava_source"},
	node_dungeon = "basenodes:cobble",
	node_dungeon_alt = "basenodes:mossycobble",
	--node_dungeon_stair = "stairs:stair_cobble",
	y_max = -256,
	y_min = -31000,
	heat_point = 92,
	humidity_point = 16,
	weight = DESERT_WEIGHT,
})
